---

- hosts: WEB:DB
  name: My Web Server Installation
  vars:
    doc_root: "/var/www/html"
    admin: "Bhargav"

  tasks:
  - name: Install Apache Packages 
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian"

  - name: Start Apache Service
    service: name=apache2 state=started
    when: ansible_os_family == "Debian"

  - name: Install HTTPD Packages 
    apt: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start HTTPD Service
    service: name=httpd state=started
    when: ansible_os_family == "RedHat"

  - name: Deploy Custom Index Web Page 
    copy: src=files/index.html dest={{doc_root}}/index.html
  
  - name: Download Background Image. 
    get_url: url="https://images4.alphacoders.com/228/thumb-1920-22896.png" dest={{doc_root}}/background.jpg mode=0755

  - name: Deploy Template Info.j2 Web Page
    template: src=templates/info.j2 dest={{doc_root}}/info.html



- hosts: DB
  name: Setting up Git Clinet
  tasks:
  - name: Install Git Packages 
    apt: name=git state=present






